### ISSUE TITLE
LCD not working

### ISSUE THREAD

**Issue by 5ft24dave** [jonsag/pi-heating#1]
The LCD code isn't working.
I have gone through to ensure I have timers, modes, continuous schedules etc all set up.
The rest of the thermostat is working perfectly.
It never initializes the LCD (connections double and triple checked, Adafruit example scripts work to drive the display properly etc)
When triggering button 1, I receive the following:

2018-12-01 16:42:10 run_script:105 pin 11: event script exited with status = 1
Traceback (most recent call last):
  File "/home/pi/pi-heating-LCD/print-to-lcd.py", line 190, in <module>
    activeNow = process_schedules(cursor, cnx, timeNow, True, False)  # (cursor, cnx, timeNow, process, verbose)
  File "/home/pi/pi-heating-LCD/modules.py", line 533, in process_schedules
    'setPoint': setPoint,
UnboundLocalError: local variable 'setPoint' referenced before assignment
2018-12-01 16:44:09 run_script:105 pin 11: event script exited with status = 1

**Comment by jonsag** [comment]
Don't have access to a machine right now. 
Will try to look into it later.
/jon

**Comment by 5ft24dave** [comment]
No hurry,
Thank you!

⁣Sent from BlueMail ​

**Comment by jonsag** [comment]
As far as I can tell it has something to do with the time not present.
Is your pi connected to the internet, ie a timeserver?
If not, you will have to either have it connected, at least at bootup, or connect a RTC, as I have done in another project: https://github.com/jonsag/piSchoolBell
I will try to look more into it.
/jon

**Comment by 5ft24dave** [comment]
It's connected to the internet and I have a DS3231 RTC on it.  Time is current.

⁣Sent from BlueMail ​

**Comment by jonsag** [comment]
Managed to create this error now.
It happens when there is no sensor found on the IP stored in the database.
It occured when i gave the RPi a new IP-number.
A quick fix is to login to the database and change IP to the RPis current one, or perhaps to set it to localhost(127.0.0.1).
mysql> UPDATE sensors SET ip = 'new ip' WHERE ip = 'old ip';
/jon

**Comment by 5ft24dave** [comment]
Cool,
Will give it a shot when I get homer.
Thanks!
